---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, load libraries}
library(tidyverse) #to read csv files
library(lubridate) # to handle dates
library(GGally) # for correlation-scatter plot matrix
library(ggfortify) # to produce residual diagnostic plots
library(rsample) # to split dataframe in training- & testing sets
library(janitor) # clean_names()
library(broom) # use broom:augment() to get tidy table with regression output, residuals, etc
library(huxtable) # to get summary table of all models produced
library(caret) # to train more advanced models (k-fold cross-validation, stepwise regression, LASSO)
library(nnet) # to calculate the maximum value of a vector
library(zoo) #to allow for time series operations
library(hms)
```


## Load the data
The whole dataset can be found on https://www.kaggle.com/olistbr/brazilian-ecommerce

```{r, load data}
customer <- read_csv("olist_customers_dataset.csv")
geolocation <- read_csv("olist_geolocation_dataset.csv")
order_item <- read_csv("olist_order_items_dataset.csv")
order_payment <- read_csv("olist_order_payments_dataset.csv")
order_review <- read_csv("olist_order_reviews_dataset.csv")
order <- read_csv("olist_orders_dataset.csv")
product <- read_csv("olist_products_dataset.csv")
seller <- read_csv("olist_sellers_dataset.csv")
product_category <- read_csv("product_category_name_translation.csv")
```

```{r}
order_seller <- left_join(order_item, seller, by = "seller_id")
order_seller_delivery <- left_join(order_seller, order, by = "order_id")
customer_seller_delivery <- left_join(order_seller_delivery, customer, by = "customer_id")

courier_data <- customer_seller_delivery %>% 
  mutate(delivery_length = round(difftime(order_delivered_customer_date,order_delivered_carrier_date,units = "days"),1)) %>% 
  mutate(delivery_length = as.numeric(str_remove(delivery_length,"days"))) %>% 
  filter(delivery_length > 0)
```

```{r}
courier_plot <- courier_data %>% 
  group_by(customer_city,seller_city) %>% 
  summarise(count = n(), median_length = median(delivery_length)) %>% 
  arrange(desc(count))
```


