---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, load libraries}
library(tidyverse) #to read csv files
library(lubridate)# to handle dates
library(skimr)
library(GGally) # for correlation-scatter plot matrix
library(ggfortify) # to produce residual diagnostic plots
library(rsample) # to split dataframe in training- & testing sets
library(janitor) # clean_names()
library(broom) # use broom:augment() to get tidy table with regression output, residuals, etc
library(huxtable) # to get summary table of all models produced
library(caret) # to train more advanced models (k-fold cross-validation, stepwise regression, LASSO)
library(nnet) # to calculate the maximum value of a vector
library(zoo) #to allow for time series operations
library(hms)
library(dplyr)
```


## Load the data
The whole dataset can be found on https://www.kaggle.com/olistbr/brazilian-ecommerce

```{r, load data}
customer <- read_csv("olist_customers_dataset.csv")
geolocation <- read_csv("olist_geolocation_dataset.csv")
order_item <- read_csv("olist_order_items_dataset.csv")
order_payment <- read_csv("olist_order_payments_dataset.csv")
order_review <- read_csv("olist_order_reviews_dataset.csv")
order <- read_csv("olist_orders_dataset.csv")
product <- read_csv("olist_products_dataset.csv")
seller <- read_csv("olist_sellers_dataset.csv")
product_category <- read_csv("product_category_name_translation.csv")
```
```{r}
#Join the dataframes
ols_raw <- order %>% 
  left_join(customer, by = "customer_id") %>% 
  left_join(order_item, by = "order_id") %>% 
  left_join(order_payment, by = "order_id") %>% 
  left_join(order_review, by = "order_id") %>% 
  left_join(product, by = "product_id") %>% 
  left_join(seller, by = "seller_id") %>% 
  left_join(product_category, by = "product_category_name") %>% 
  clean_names()

```


```{r}
cred_inst <- order_payment %>% 
  group_by(order_id) %>% 
  mutate(total_payment = sum(payment_value),
         payment_perc = payment_value / total_payment) %>% 
  ungroup() %>% 
  filter(payment_installments >1 ) %>% 
  mutate(price_range = ifelse(total_payment <= 100, "<100", 
                               ifelse(total_payment <= 500, "100-500",
                                      ifelse(total_payment <= 1000 , "500-1000",
                                             ifelse(total_payment <= 5000, "1000-5000",
                                      ">5000"))))) %>% 
  group_by(price_range) %>% 
  summarise(count = n(),
            mean_ins = mean(payment_installments),
            median_ins = median(payment_installments),
            average_perc = mean(payment_perc)) 


cred_inst$price_range <- factor(cred_inst$price_range,levels = c("<100","100-500","500-1000","1000-5000",">5000"))
cred_inst


```






```{r}
voucher <- order_payment %>% 
  group_by(order_id) %>% 
  mutate(total_payment = sum(payment_value),
         payment_perc = payment_value / total_payment) %>% 
  ungroup() %>% 
  filter(payment_type == "voucher" ) %>% 
  group_by(order_id) %>% 
  mutate(voucher_total_value = sum(payment_value),
         value_left = total_payment - voucher_total_value)

voucher_value_left <- voucher %>% 
  select(order_id,value_left) %>% 
  distinct()

cred_voucher <- order_payment %>% 
  left_join(voucher_value_left, by = "order_id") %>% 
  filter(!is.na(value_left) & value_left > 0 & payment_type == "credit_card") %>% 
  mutate(value_range = ifelse(value_left <= 50, "<50", 
                               ifelse(value_left <= 100, "50-100",
                                      ifelse(value_left <= 200 , "100-200",
                                             ifelse(value_left <= 500, "200-500",
                                                    ifelse(value_left <= 5000, "500-5000",
                                      ">5000")))))) %>% 
  group_by(value_range) %>% 
  summarise(count = n(),
            mean_ins = mean(payment_installments),
            median_ins = median(payment_installments)) %>% 
  mutate(voucher = rep("Yes",5))

cred_voucher$value_range <- factor(cred_voucher$value_range,levels = c("<50","50-100","100-200","200-500","500-5000",">5000"))
cred_voucher
```





```{r}

cred_no_voucher <- order_payment %>% 
  group_by(order_id) %>% 
  mutate(total_payment = sum(payment_value),
         payment_perc = payment_value / total_payment) %>% 
  ungroup() %>% 
  left_join(voucher_value_left, by = "order_id") %>% 
  filter(is.na(value_left) & payment_type == "credit_card") %>% 
  mutate(value_range = ifelse(total_payment <= 50, "<50", 
                               ifelse(total_payment <= 100, "50-100",
                                      ifelse(total_payment <= 200 , "100-200",
                                             ifelse(total_payment <= 500, "200-500",
                                                    ifelse(total_payment <= 5000, "500-5000",
                                      ">5000")))))) %>% 
  group_by(value_range) %>% 
  summarise(count = n(),
            mean_ins = mean(payment_installments),
            median_ins = median(payment_installments)) %>% 
  mutate(voucher = rep("No",6))

cred_no_voucher$value_range <- factor(cred_no_voucher$value_range,levels = c("<50","50-100","100-200","200-500","500-5000",">5000"))
cred_no_voucher


```



```{r}
voucher_ins <- rbind(cred_voucher,cred_no_voucher)
voucher_ins$voucher <- factor(voucher_ins$voucher, levels = c("Yes","No"))
```

```{r,fig.height=6, fig.width=6}

label1 <- "At very high price, using credit cards \n do not necessarily link to affordability."
label2 <- "For the same value, customers pay with more installments \n if it's the remaining value after deducting voucher."

ggplot(data = voucher_ins, aes(x = value_range, y = median_ins,
                               colour = voucher, group = voucher))+
  geom_point() +
  geom_line() +
  labs(title = "Vouchers entice people to purchase even if they need more installments",
       subtitle = "Median number of installments used by customers paying with credit cards for the total price or the remaining value after using vouchers",
  x ="Value Range" , y = "Median Number of Installments",
       colour = "Voucher") +
  
  geom_curve(
    data = data.frame(x = 5.5, y = 3.2, xend = 6, yend = 4.3),
    mapping = aes(x = x, y = y, xend = xend, yend = yend),
    colour = "darkred",
    size = 0.5,
    curvature = 0.25,
    arrow = arrow(length = unit(2, "mm"), type = "closed"),
    inherit.aes = FALSE
  ) +
  
   geom_curve(
    data = data.frame(x = 2.7, y = 4, xend = 2, yend = 4.4),
    mapping = aes(x = x, y = y, xend = xend, yend = yend),
    colour = "darkred",
    size = 0.5,
    curvature = -0.25,
    arrow = arrow(length = unit(2, "mm"), type = "closed"),
    inherit.aes = FALSE
  ) +
  
  geom_text(
    data = data.frame(x = 5.5, y = 3, label = label1),
    aes(x = x, y = y, label = label),
    colour="navyblue",
    family="Lato",
    hjust = 0.5,
    lineheight = .8,
    inherit.aes = FALSE
  ) +
  
  annotate("rect", xmin = 2.9, xmax = 3.1, ymin = 2.8, ymax = 4.2, alpha = 0.2) +
  annotate("text", x = 2, y = 4.8, label = label2, colour = "orange") +
  theme_minimal() +
  theme(strip.text = element_text(color = "white",size = 20),
        strip.text.y = element_text(angle=0),
        plot.title = element_text(size = 15),
        plot.subtitle = element_text(size = 10),
        axis.title.x = element_text(hjust = 0.5, size = 10),
        axis.title.y = element_text(hjust = 0.5, size = 10))
```



