---
title: "Olist_ecommerce_master"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, load libraries}
library(tidyverse) #to read csv files
library(lubridate)# to handle dates
library(skimr)
library(GGally) # for correlation-scatter plot matrix
library(ggfortify) # to produce residual diagnostic plots
library(rsample) # to split dataframe in training- & testing sets
library(janitor) # clean_names()
library(broom) # use broom:augment() to get tidy table with regression output, residuals, etc
library(huxtable) # to get summary table of all models produced
library(caret) # to train more advanced models (k-fold cross-validation, stepwise regression, LASSO)
library(nnet) # to calculate the maximum value of a vector
library(zoo) #to allow for time series operations
library(hms)
library(dplyr)
```


## Load the data
The whole dataset can be found on https://www.kaggle.com/olistbr/brazilian-ecommerce

```{r, load data}
customer <- read_csv("olist_customers_dataset.csv")
geolocation <- read_csv("olist_geolocation_dataset.csv")
order_item <- read_csv("olist_order_items_dataset.csv")
order_payment <- read_csv("olist_order_payments_dataset.csv")
order_review <- read_csv("olist_order_reviews_dataset.csv")
order <- read_csv("olist_orders_dataset.csv")
product <- read_csv("olist_products_dataset.csv")
seller <- read_csv("olist_sellers_dataset.csv")
product_category <- read_csv("product_category_name_translation.csv")
```
```{r}
#Join the dataframes
ols_raw <- order %>% 
  left_join(customer, by = "customer_id") %>% 
  left_join(order_item, by = "order_id") %>% 
  left_join(order_payment, by = "order_id") %>% 
  left_join(order_review, by = "order_id") %>% 
  left_join(product, by = "product_id") %>% 
  left_join(seller, by = "seller_id") %>% 
  left_join(product_category, by = "product_category_name") %>% 
  clean_names()

```

```{r}
ols_clean <- ols_raw %>% 
  #Comment message in Portuguese
  select(-review_comment_message)
```

```{r huxtable-stuff, include=FALSE}

#I start all my markdowm files by laoding the libraries I use throughout. This is for quick reference
options("huxtable.knit_print_df" = FALSE)

if(!is.element("tidyverse", installed.packages()[,1]))
{  install.packages("tidyverse")}
if(!is.element("cluster", installed.packages()[,1]))
{  install.packages("cluster")}
if(!is.element("factoextra", installed.packages()[,1]))
{  install.packages("factoextra")}
if(!is.element("Hmisc", installed.packages()[,1]))
{  install.packages("Hmisc")}

require(tidyverse)
require(Hmisc)
require(digest)
require(cluster)    # clustering algorithms
require(factoextra) # an umbrealla library for clustering algorithms & visualizations
require(hrbrthemes)
```

```{r distinct orders}
#There are multiple entries for one order because when we joined order with order_payment, there could be multiple payment methods for one order, thus resulting in multiple rows for one order. Here we only keep one row for each order and sum up the total payment amount. 

order_total_amount <- ols_clean %>% 
  group_by(order_id) %>% 
  summarise(total_payment = sum(payment_value))


purchase_info <- ols_clean %>% 
  select(order_id,
         customer_unique_id,
         review_score,
         product_category_name_english,
         customer_city) %>% 
  distinct(order_id, .keep_all = TRUE)

purchase_info <- left_join(purchase_info,order_total_amount,by = "order_id") 
```

```{r customer info}
customer_purchase <- purchase_info %>% 
  count(customer_unique_id, product_category_name_english) %>% 
  group_by(customer_unique_id) %>% 
  mutate(total_purchase = sum(n),
         category_percent = round((n/total_purchase)*100,2)) %>% 
  select(-n, -total_purchase) %>% 
  pivot_wider(names_from = product_category_name_english,
              values_from = category_percent)

unique_customer <- customer %>% 
  distinct(customer_unique_id,.keep_all = TRUE) %>% 
  select(-customer_id)

unique_customer_purchase <- purchase_info %>% 
  group_by(customer_unique_id) %>% 
  summarise(total_amount = sum(total_payment))

unique_customer_review <- purchase_info %>% 
  group_by(customer_unique_id) %>% 
  summarise(average_review_score = mean(review_score))

customer_info <- customer_purchase %>% 
  left_join(unique_customer, by = "customer_unique_id") %>% 
  left_join(unique_customer_purchase, by = "customer_unique_id") %>% 
  left_join(unique_customer_review, by = "customer_unique_id") %>% 
  ungroup() %>% 
  select(-customer_zip_code_prefix,-customer_state)

customer_info[is.na(customer_info)] <- 0


```


```{r}
to_graph <- customer_info %>% 
  select(customer_unique_id, customer_city, total_amount, average_review_score) %>% 
  mutate(rating = ifelse(average_review_score < 3, "low","high"))

#to_graph$rating <- factor(to_graph$rating, levels = c("low","medium","high"))           
```

```{r}
brazil_pop <- read_csv("Brazil_pop.csv")
brazil_pop$name <- tolower(brazil_pop$name)
names(brazil_pop)[names(brazil_pop) == '2021'] <- 'population'
```


```{r}
to_graph2 <- to_graph %>% 
  group_by(customer_city) %>% 
  summarise(med_city_spend = median(total_amount), avg_city_spend = mean(total_amount) , obs = n(), tot_spend = sum(total_amount)) %>% 
  filter(obs > 1000)
```

```{r}
to_graph3 <- left_join(to_graph2, brazil_pop, customer, by = c("customer_city" = "name"))
to_graph3 <- to_graph3 %>% 
  mutate(spend_pp = tot_spend/population)
```

```{r}
ggplot(data = to_graph3, aes(x = reorder(customer_city, -spend_pp), y = spend_pp)) + geom_col() + labs(x = "City", y = "Spending per person")
```

```{r}
ggplot(data = to_graph2, aes(x = reorder(customer_city, -med_city_spend), y = med_city_spend)) + geom_col() + labs(x = "City", y = "Median spend in Brazilian Real", title = "Median spending is similar across cities")
```

```{r}
rating_graph2 <- to_graph %>% 
  group_by(rating) %>% 
  summarise(med_review_spend = median(total_amount), avg_review_spend = mean(total_amount) , obs = n(),   tot_spend = sum(total_amount)) 
rating_graph2
```
```{r}
rating_graph2 %>% 
  ggplot(aes(x = avg_review_spend, y = med_review_spend)) + 
  geom_col() + 
  labs(x = "Score", y = "Median spend in Brazilian Real", title = "Median spending is similar across scores")
```



```{r}
rating_cat <- customer_info %>% 
  mutate(rating = ifelse(average_review_score <=2, "low", ifelse(average_review_score < 4, "medium","high"))) %>%  
  pivot_longer(cols = bed_bath_table:la_cuisine, names_to = "category", values_to = "perc") %>% 
  filter(perc != 0 & category != "NA")

high_rating_cat <- rating_cat %>% 
  filter(rating == "high") %>% 
  count(category) %>% 
  slice_max(n, n = 10) %>% 
  mutate(rating = "high")

medium_rating_cat <- rating_cat %>% 
  filter(rating == "medium") %>% 
  count(category) %>% 
  slice_max(n, n = 10) %>% 
  mutate(rating = "medium")

low_rating_cat <- rating_cat %>% 
  filter(rating == "low") %>% 
  count(category) %>% 
  slice_max(n, n = 10) %>% 
  mutate(rating = "low")

rating_cat <- high_rating_cat %>% 
  
  rbind(low_rating_cat) %>% 
  mutate(rating = factor(rating,levels = c("high","low")))

ggplot(data = rating_cat, aes(y = tidytext::reorder_within(category, n, rating), x = n,
                              fill = category)) +
  geom_col() +
  tidytext::scale_y_reordered() +
  facet_wrap(~rating, scales = "free_y", nrow =3)
```

```{r}
cred_inst <- order_payment %>% 
  group_by(order_id) %>% 
  mutate(total_payment = sum(payment_value),
         payment_perc = payment_value / total_payment) %>% 
  ungroup() %>% 
  filter(payment_installments >1 ) %>% 
  mutate(price_range = ifelse(total_payment <= 100, "<100", 
                               ifelse(total_payment <= 500, "100-500",
                                      ifelse(total_payment <= 1000 , "500-1000",
                                             ifelse(total_payment <= 5000, "1000-5000",
                                      ">5000"))))) %>% 
  group_by(price_range) %>% 
  summarise(count = n(),
            mean_ins = mean(payment_installments),
            median_ins = median(payment_installments),
            average_perc = mean(payment_perc)) 


cred_inst$price_range <- factor(cred_inst$price_range,levels = c("<100","100-500","500-1000","1000-5000",">5000"))
cred_inst


```

```{r}
cred_inst %>% ggplot(aes(x = total_payment)) +
  geom_density()
```


```{r}
cred_inst %>% ggplot(aes(x = price_range, y = median_ins)) +
  geom_point() +
  geom_line(group = 1) +
  labs(x ="Price Range" , y = "Median Number of Installments")
```

```{r}
voucher <- order_payment %>% 
  group_by(order_id) %>% 
  mutate(total_payment = sum(payment_value),
         payment_perc = payment_value / total_payment) %>% 
  ungroup() %>% 
  filter(payment_type == "voucher" ) %>% 
  group_by(order_id) %>% 
  mutate(voucher_total_value = sum(payment_value),
         value_left = total_payment - voucher_total_value)

voucher_value_left <- voucher %>% 
  select(order_id,value_left) %>% 
  distinct()

cred_voucher <- order_payment %>% 
  left_join(voucher_value_left, by = "order_id") %>% 
  filter(!is.na(value_left) & value_left > 0 & payment_type == "credit_card") %>% 
  mutate(value_range = ifelse(value_left <= 50, "<50", 
                               ifelse(value_left <= 100, "50-100",
                                      ifelse(value_left <= 200 , "100-200",
                                             ifelse(value_left <= 500, "200-500",
                                                    ifelse(value_left <= 5000, "500-5000",
                                      ">5000")))))) %>% 
  group_by(value_range) %>% 
  summarise(count = n(),
            mean_ins = mean(payment_installments),
            median_ins = median(payment_installments)) %>% 
  mutate(voucher = rep("Yes",5))

cred_voucher$value_range <- factor(cred_voucher$value_range,levels = c("<50","50-100","100-200","200-500","500-5000",">5000"))
cred_voucher
```

```{r}
cred_voucher %>% ggplot(aes(x = value_range, y = median_ins)) +
  geom_point() +
  geom_line(group = 1) +
  labs(x ="Value Paid Exluding Voucher" , y = "Median Number of Installments")

```



```{r}

cred_no_voucher <- order_payment %>% 
  group_by(order_id) %>% 
  mutate(total_payment = sum(payment_value),
         payment_perc = payment_value / total_payment) %>% 
  ungroup() %>% 
  left_join(voucher_value_left, by = "order_id") %>% 
  filter(is.na(value_left) & payment_type == "credit_card") %>% 
  mutate(value_range = ifelse(total_payment <= 50, "<50", 
                               ifelse(total_payment <= 100, "50-100",
                                      ifelse(total_payment <= 200 , "100-200",
                                             ifelse(total_payment <= 500, "200-500",
                                                    ifelse(total_payment <= 5000, "500-5000",
                                      ">5000")))))) %>% 
  group_by(value_range) %>% 
  summarise(count = n(),
            mean_ins = mean(payment_installments),
            median_ins = median(payment_installments)) %>% 
  mutate(voucher = rep("No",6))

cred_no_voucher$value_range <- factor(cred_no_voucher$value_range,levels = c("<50","50-100","100-200","200-500","500-5000",">5000"))
cred_no_voucher


```


```{r}
cred_no_voucher %>% ggplot(aes(x = value_range, y = median_ins)) +
  geom_point() +
  geom_line(group = 1) +
  labs(x ="Median Price" , y = "Number of Installments")

```

```{r}
voucher_ins <- rbind(cred_voucher,cred_no_voucher)
voucher_ins$voucher <- factor(voucher_ins$voucher, levels = c("Yes","No"))
```

```{r,fig.height=6, fig.width=6}

label1 <- "At very high price, using credit cards \n do not necessarily link to affordability."
label2 <- "For the same value, customers pay with more installments \n if it's the remaining value after deducting voucher."

ggplot(data = voucher_ins, aes(x = value_range, y = median_ins,
                               colour = voucher, group = voucher))+
  geom_point() +
  geom_line() +
  labs(title = "Vouchers entice people to purchase even if they need more installments",
       subtitle = "Median number of installments used by customers paying with credit cards for the total price or the remaining value after using vouchers",
  x ="Value Range" , y = "Median Number of Installments",
       colour = "Voucher") +
  
  geom_curve(
    data = data.frame(x = 5.5, y = 3.2, xend = 6, yend = 4.3),
    mapping = aes(x = x, y = y, xend = xend, yend = yend),
    colour = "white",
    size = 0.5,
    curvature = 0.25,
    arrow = arrow(length = unit(2, "mm"), type = "closed"),
    inherit.aes = FALSE
  ) +
  
   geom_curve(
    data = data.frame(x = 2.7, y = 4, xend = 2, yend = 4.4),
    mapping = aes(x = x, y = y, xend = xend, yend = yend),
    colour = "white",
    size = 0.5,
    curvature = -0.25,
    arrow = arrow(length = unit(2, "mm"), type = "closed"),
    inherit.aes = FALSE
  ) +
  
  geom_text(
    data = data.frame(x = 5.5, y = 3, label = label1),
    aes(x = x, y = y, label = label),
    colour="#F5BDAC",
    family="Lato",
    hjust = 0.5,
    lineheight = .8,
    inherit.aes = FALSE
  ) +
  
  annotate("rect", xmin = 2.9, xmax = 3.1, ymin = 2.8, ymax = 4.2, alpha = 0) +
  annotate("text", x = 2, y = 4.8, label = label2, colour = "#CAE2F5") +
  
  theme_ft_rc(grid="", strip_text_face = "bold") +
  theme(strip.text = element_text(color = "white",size = 20),
        strip.text.y = element_text(angle=0),
        plot.title = element_text(size = 15),
        plot.subtitle = element_text(size = 10),
        axis.title.x = element_text(hjust = 0.5, size = 10),
        axis.title.y = element_text(hjust = 0.5, size = 10))
```



